export const DUMMY_USERS = [
  {
    id: '1',
    name: 'Sarah',
    age: 26,
    distance: '0.2 mi away',
    job: 'Marketing Specialist',
    bio: 'Love hiking and exploring new coffee shops. Looking for a casual talk.',
    image: 'https://randomuser.me/api/portraits/women/1.jpg',
    vibes: ['Coffee', 'Walk'],
    note: 'Sitting at the window seat in Starbucks. Wearing a green jacket!',
    languages: ['English', 'Spanish'],
    status: 'online',
  },
  {
    id: '2',
    name: 'Marcus',
    age: 31,
    distance: '0.5 mi away',
    job: 'Software Engineer',
    bio: 'Digital nomad passing through. Any book recommendations for sci-fi?',
    image: 'https://randomuser.me/api/portraits/men/2.jpg',
    vibes: ['Grab A Bite', 'Event'],
    languages: ['English', 'German'],
    status: 'away',
  },
  {
    id: '3',
    name: 'Emma',
    age: 26,
    distance: '0.8 mi away',
    job: 'Art Student',
    bio: 'Art student looking for sketch buddies in the park this afternoon.',
    image: 'https://randomuser.me/api/portraits/women/3.jpg',
    vibes: ['Coffee', 'Explore The Area'],
    languages: ['English', 'French'],
    status: 'online',
  },
  {
    id: '4',
    name: 'Alex',
    age: 26,
    distance: '1.2 mi away',
    job: 'Designer',
    bio: 'Designer by day, gamer by night. Let’s grab a drink!',
    image: 'https://randomuser.me/api/portraits/men/4.jpg',
    vibes: ['Drink', 'Just Connect'],
    languages: ['English'],
    status: 'offline',
  },
];

export const DUMMY_CHATS = [
  {
    id: '1',
    userId: '1',
    name: 'Sarah',
    age: 26,
    lastMessage: 'Sure, see you soon!',
    time: '2h ago',
    unread: true,
    image: 'https://randomuser.me/api/portraits/women/1.jpg',
  },
  {
    id: '2',
    userId: '4',
    name: 'Alex',
    age: 26,
    lastMessage: 'Sounds good! See you there.',
    time: 'Today',
    unread: false,
    image: 'https://randomuser.me/api/portraits/men/4.jpg',
  },
  {
    id: '3',
    userId: '3',
    name: 'Emma',
    age: 26,
    lastMessage: 'After work, keeping things easy',
    time: 'Yesterday',
    unread: false,
    image: 'https://randomuser.me/api/portraits/women/3.jpg',
  },
];

export const DUMMY_MESSAGES = [
  {
    id: '1',
    text: 'Hey! I\'m near Westside Coffee. Grab a drink?',
    senderId: '1',
    time: '7:15pm',
  },
  {
    id: '2',
    text: 'Sure, I\'ll head over. Grabbing my stuff.',
    senderId: 'me',
    time: '7:16pm',
  },
  {
    id: '3',
    text: 'Sounds good! See you there.',
    senderId: '1',
    time: '7:17pm',
  },
  {
    id: '4',
    text: 'I\'ll be there in 10min. You at a table?',
    senderId: 'me',
    time: '7:20pm',
  },
];
